/* Microchip Technology Inc. and its subsidiaries.  You may use this software 
 * and any derivatives exclusively with Microchip products. 
 * 
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS".  NO WARRANTIES, WHETHER 
 * EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED 
 * WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A 
 * PARTICULAR PURPOSE, OR ITS INTERACTION WITH MICROCHIP PRODUCTS, COMBINATION 
 * WITH ANY OTHER PRODUCTS, OR USE IN ANY APPLICATION. 
 *
 * IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, 
 * INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND 
 * WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS 
 * BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE 
 * FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS 
 * IN ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF 
 * ANY, THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * MICROCHIP PROVIDES THIS SOFTWARE CONDITIONALLY UPON YOUR ACCEPTANCE OF THESE 
 * TERMS. 
 */

/*******************************************************************************
  This source file has NOT been generated by the MHC
 *******************************************************************************/

/* 
 * File:   
 * Author: 
 * Comments:
 * Revision history: 
 */

// *****************************************************************************
// *****************************************************************************
// Section: Included Files 
// *****************************************************************************
// *****************************************************************************
#include "mcc.h"
#include "rbuffer.h"

// *****************************************************************************
// *****************************************************************************
// Section: Global Data Definitions
// *****************************************************************************
// *****************************************************************************
extern unsigned char RBUFFER[RING_BUFFER_SIZE + 1];


// *****************************************************************************
// *****************************************************************************
// Section: User Functions
// *****************************************************************************
// *****************************************************************************

// Comment a function definition and leverage automatic documentation 
/**
  <p><b>Function:</b></p>

  <p><b>Summary:</b></p>

  <p><b>Description:</b></p>

  <p><b>Remarks:</b></p>
 */
// TODO Insert function definitions (right here) to leverage live documentation
int BufferIsFull(void){
	if (NumberOfElem() == RING_BUFFER_SIZE){
		return 1;
	}	
	else {
		return 0;
	}
}

int BufferIsEmpty(void){
	if (next_elem == first_elem){
		return 1;
	}
	else{
		return 0;
	}
}

int NumberOfElem(void){
	if (next_elem >= first_elem){
       	return (next_elem - first_elem);
	}
        else{
        	return (RING_BUFFER_SIZE - next_elem + first_elem);
	}
}

void putElement(unsigned char data){
	if (!BufferIsFull()){
		RBUFFER[next_elem] = data;
			
		if(next_elem != RING_BUFFER_SIZE){
			next_elem ++;
		}
		else{
			next_elem = 0;
		}
	}
}

char getElement(void){
	int data;
	if (!BufferIsEmpty()){
		data = RBUFFER[first_elem];
		if (first_elem != RING_BUFFER_SIZE){
			first_elem ++;
		}
		else{
			first_elem = 0;
		}
	}
	else{
		data = 0;
	}
	return data;
}

void clearBuffer(void){
	first_elem = 0;
	next_elem = 0;
	RBUFFER[0] = 0;
}

//EOF